### ISSUE TITLE
APP: Create SchoolDeviceRequests view

### ISSUE THREAD

**Issue by sandroschutt** [sandroschutt/r3e-app#130]
- [x] Available to ADMIN and ESCOLA
- [x] ADMIN can view, edit, delete, approve reprove
- [x] ESCOLA can create (request) and cancel

#### Subtasks
- [x] route
- [x] menu item
- [x] view
- [x] class
- [x] table
- [x] actions
    - [x] APPROVE
    - [x] REPROVE
    - [x] VIEW
    - [x] DELETE

**Comment by sandroschutt** [comment]
#### DEPENDS ON:
- https://github.com/sandroschutt/r3e-api/issues/55
-
