### ISSUE TITLE
APP: Create SchoolDeviceRequest single view

### ISSUE THREAD

**Issue by sandroschutt** [sandroschutt/r3e-app#131]
- [x] Availabel to ADMIN and ESCOLA
- [x] ADMIN can view, edit, delete, approve reprove
- [x] ESCOLA can create (request) and cancel

#### Subtasks
- [x] route
- [x] view
- [x] student card
- [x] school card
- [x] device card
- [x] action buttons

**Comment by sandroschutt** [comment]
#### DEPENDS ON
- https://github.com/sandroschutt/r3e-app/issues/130
